using System;
using System.Collections.Generic;

namespace FemVoiceStudio.Models
{
    /// <summary>
    /// Represents a scheduled training session for a specific day.
    /// </summary>
    public class ScheduledSession
    {
        /// <summary>
        /// The date for this scheduled session.
        /// </summary>
        public DateTime Date { get; set; }
        
        /// <summary>
        /// Day of week (0 = Sunday, 6 = Saturday).
        /// </summary>
        public DayOfWeek DayOfWeek => Date.DayOfWeek;
        
        /// <summary>
        /// Type of training day.
        /// </summary>
        public TrainingDayType DayType { get; set; }
        
        /// <summary>
        /// Training load configuration.
        /// </summary>
        public TrainingLoad? Load { get; set; }
        
        /// <summary>
        /// Whether this session has been completed.
        /// </summary>
        public bool IsCompleted { get; set; }
        
        /// <summary>
        /// Reference to the actual training session if completed.
        /// </summary>
        public int? CompletedSessionId { get; set; }
        
        /// <summary>
        /// User's subjective report if submitted.
        /// </summary>
        public SubjectiveReport? SubjectiveReport { get; set; }
        
        /// <summary>
        /// Explanation for why this day is scheduled this way.
        /// Generated by WeeklyPlannerEngine.
        /// </summary>
        public string? WeeklyExplanation { get; set; }
        
        /// <summary>
        /// Recommended exercise IDs for this session (based on complexity level).
        /// </summary>
        public List<int> RecommendedExerciseIds { get; set; } = new();
        
        /// <summary>
        /// Whether this day was adjusted from the original plan.
        /// </summary>
        public bool WasAdjusted { get; set; }
        
        /// <summary>
        /// Reason for adjustment if any.
        /// </summary>
        public string? AdjustmentReason { get; set; }
        
        /// <summary>
        /// Display name for the day type.
        /// </summary>
        public string DayTypeDisplayName => DayType switch
        {
            TrainingDayType.Progression => "Progresjon",
            TrainingDayType.Consolidation => "Konsolidering",
            TrainingDayType.Light => "Lett økt",
            TrainingDayType.Recovery => "Restitusjon",
            TrainingDayType.Rest => "Hviledag",
            TrainingDayType.Micro => "Mikro-trening",
            _ => "Planlagt"
        };
    }
    
    /// <summary>
    /// Weekly schedule generated by WeeklyPlannerEngine.
    /// Contains 7 days of planned sessions with explanations.
    /// </summary>
    public class WeeklySchedule
    {
        /// <summary>
        /// Unique identifier.
        /// </summary>
        public int Id { get; set; }
        
        /// <summary>
        /// The week start date (Monday).
        /// </summary>
        public DateTime WeekStartDate { get; set; }
        
        /// <summary>
        /// The week end date (Sunday).
        /// </summary>
        public DateTime WeekEndDate { get; set; }
        
        /// <summary>
        /// Scheduled sessions for each day of the week.
        /// </summary>
        public List<ScheduledSession> Sessions { get; set; } = new();
        
        /// <summary>
        /// Whether this is a recovery week (reduced intensity).
        /// </summary>
        public bool IsRecoveryWeek { get; set; }
        
        /// <summary>
        /// Overall explanation for the week's structure.
        /// Generated by SmartCoach logic.
        /// </summary>
        public string? WeekExplanation { get; set; }
        
        /// <summary>
        /// Total load score for the week.
        /// </summary>
        public double TotalWeeklyLoad { get; set; }
        
        /// <summary>
        /// Number of progression sessions.
        /// </summary>
        public int ProgressionSessionCount => Sessions.Count(s => s.DayType == TrainingDayType.Progression);
        
        /// <summary>
        /// Number of consolidation sessions.
        /// </summary>
        public int ConsolidationSessionCount => Sessions.Count(s => s.DayType == TrainingDayType.Consolidation);
        
        /// <summary>
        /// Number of light sessions.
        /// </summary>
        public int LightSessionCount => Sessions.Count(s => s.DayType == TrainingDayType.Light);
        
        /// <summary>
        /// Number of rest days.
        /// </summary>
        public int RestDayCount => Sessions.Count(s => s.DayType == TrainingDayType.Rest);
        
        /// <summary>
        /// Number of completed sessions.
        /// </summary>
        public int CompletedSessionCount => Sessions.Count(s => s.IsCompleted);
        
        /// <summary>
        /// Progress percentage (completed / scheduled non-rest sessions).
        /// </summary>
        public double ProgressPercentage
        {
            get
            {
                var scheduled = Sessions.Count(s => s.DayType != TrainingDayType.Rest);
                return scheduled > 0 ? (double)CompletedSessionCount / scheduled * 100 : 0;
            }
        }
        
        /// <summary>
        /// Gets session for a specific date.
        /// </summary>
        public ScheduledSession? GetSessionForDate(DateTime date)
        {
            return Sessions.Find(s => s.Date.Date == date.Date);
        }
        
        /// <summary>
        /// Gets session for a specific day of week.
        /// </summary>
        public ScheduledSession? GetSessionForDayOfWeek(DayOfWeek dayOfWeek)
        {
            return Sessions.Find(s => s.DayOfWeek == dayOfWeek);
        }
    }
    
    /// <summary>
    /// Target adjustments recommended by ProgressionEngine.
    /// </summary>
    public class TargetAdjustment
    {
        /// <summary>
        /// New target minimum pitch (Hz). Null if no change.
        /// </summary>
        public double? TargetPitchMin { get; set; }
        
        /// <summary>
        /// New target maximum pitch (Hz). Null if no change.
        /// </summary>
        public double? TargetPitchMax { get; set; }
        
        /// <summary>
        /// New target resonance score. Null if no change.
        /// </summary>
        public double? TargetResonanceScore { get; set; }
        
        /// <summary>
        /// New target prosody range. Null if no change.
        /// </summary>
        public double? TargetProsodyRange { get; set; }
        
        /// <summary>
        /// Whether any pitch adjustment was made.
        /// </summary>
        public bool HasPitchAdjustment => TargetPitchMin.HasValue || TargetPitchMax.HasValue;
        
        /// <summary>
        /// Pitch adjustment in Hz (positive = increase).
        /// </summary>
        public double? PitchAdjustmentHz
        {
            get
            {
                if (TargetPitchMin.HasValue && TargetPitchMax.HasValue)
                    return (TargetPitchMin.Value + TargetPitchMax.Value) / 2;
                return null;
            }
        }
        
        /// <summary>
        /// Creates a default (no change) adjustment.
        /// </summary>
        public static TargetAdjustment None => new();
        
        /// <summary>
        /// Creates a pitch zone increase adjustment.
        /// </summary>
        public static TargetAdjustment CreatePitchIncrease(double minHz, double maxHz)
        {
            return new TargetAdjustment
            {
                TargetPitchMin = minHz,
                TargetPitchMax = maxHz
            };
        }
        
        /// <summary>
        /// Creates a resonance improvement adjustment.
        /// </summary>
        public static TargetAdjustment CreateResonanceImprovement(double targetScore)
        {
            return new TargetAdjustment
            {
                TargetResonanceScore = targetScore
            };
        }
    }
    
    /// <summary>
    /// Complete progression decision output from ProgressionEngine.
    /// </summary>
    public class ProgressionDecisionResult
    {
        /// <summary>
        /// The selected progression mode for the next session/week.
        /// </summary>
        public ProgressionMode Mode { get; set; }
        
        /// <summary>
        /// Human-readable explanation of the decision.
        /// </summary>
        public string Reasoning { get; set; } = string.Empty;
        
        /// <summary>
        /// Target adjustments for next phase.
        /// </summary>
        public TargetAdjustment NextTargets { get; set; } = new();
        
        /// <summary>
        /// Whether progression is allowed.
        /// False if any gate is closed.
        /// </summary>
        public bool AllowProgression { get; set; } = true;
        
        /// <summary>
        /// Warning messages if any gates failed.
        /// </summary>
        public List<string> GateWarnings { get; set; } = new();
        
        /// <summary>
        /// When this decision was made.
        /// </summary>
        public DateTime DecidedAt { get; set; } = DateTime.Now;
        
        /// <summary>
        /// Consecutive stable sessions count used in decision.
        /// </summary>
        public int ConsecutiveStableSessions { get; set; }
        
        /// <summary>
        /// Whether the decision was based on subjective override.
        /// </summary>
        public bool WasSubjectiveOverride { get; set; }
        
        // ============================
        // Complexity Integration
        // ============================
        
        /// <summary>
        /// Recommended speech complexity level based on session evaluation.
        /// </summary>
        public SpeechComplexityLevel RecommendedComplexityLevel { get; set; } = SpeechComplexityLevel.IsolatedSounds;
        
        /// <summary>
        /// Whether complexity level can advance based on clinical criteria.
        /// </summary>
        public bool ComplexityCanAdvance { get; set; }
        
        /// <summary>
        /// Reason for complexity recommendation.
        /// </summary>
        public string ComplexityReason { get; set; } = string.Empty;
        
        /// <summary>
        /// Current complexity evaluation details.
        /// </summary>
        public ComplexityEvaluation? ComplexityEvaluation { get; set; }
        
        /// <summary>
        /// Creates a maintenance mode decision.
        /// </summary>
        public static ProgressionDecisionResult Maintain(string reason)
        {
            return new ProgressionDecisionResult
            {
                Mode = ProgressionMode.Maintenance,
                Reasoning = reason,
                AllowProgression = false
            };
        }
        
        /// <summary>
        /// Creates a recovery mode decision.
        /// </summary>
        public static ProgressionDecisionResult Recover(string reason)
        {
            return new ProgressionDecisionResult
            {
                Mode = ProgressionMode.HealthRecovery,
                Reasoning = reason,
                AllowProgression = false
            };
        }
    }
}
